### ISSUE TITLE
Build View for the Chess board

### ISSUE THREAD

**Issue by apolishch** [apolishch/dreamteam#14]
- [x] Have an empty chess board on games#show page 
       (8x8 grid bottom left is black)

Don't worry about pieces just yet

**Comment by CharlieTyler** [comment]
Quick view I made for the chess board - [Chess board](https://gist.github.com/CharlieTyler/49b22d4565eb10e5e104315de4efca3d)
Feel free to download and have a look - needs more work before finishing the page.
