### ISSUE TITLE
Create a PaaS application using a provider of your choice

### ISSUE THREAD

**Issue by apolishch** [apolishch/dreamteam#4]
(this will probably be easisest with Heroku)
- [x] Invite team to collaborate

**Comment by mahoneyj02** [comment]
Is this completed? If so, what is the link to the Heroku app?

**Comment by mahoneyj02** [comment]
Everything seems to be good on this. No one has pushed to Heroku yet, from what I can tell. Is that what everyone else is seeing?

**Comment by CharlieTyler** [comment]
Yep @mahoneyj02 , I think we need circle or something similar for our CD before we can hook up heroku. But not sure.

**Comment by zacjones93** [comment]
I'll look into this when I get started on CI, planning on giving it a go tonight
