### ISSUE TITLE
Create Wireframe

### ISSUE THREAD

**Issue by apolishch** [apolishch/dreamteam#8]
Run past team, bring to discussion.
There are loads of tools you could use for this. Loads of designers I know swear by Balsamiq

**Comment by CharlieTyler** [comment]
Made a start on the wire-frames, keen for anyone else to add their input if you want. Produced in Balsamiq, [link to file](https://drive.google.com/open?id=1vKAtJJsTur5fzLuIEVLX-S_cr7tsY-LY), if you want to add anything. 

* I haven't included the log in and out pages as they are pretty simple
* I have added probably more info than is needed on the user page

Please view the pdf - [Dreamteam-chess-app.pdf](https://github.com/apolishch/dreamteam/files/1768393/Dreamteam-chess-app.pdf)

**Comment by mahoneyj02** [comment]
@CharlieTyler, everything looks great! My feedback:
When a user is signed in (e.g., profile page, active game page)
- change `sign in` button to `sign out`
- change `sign up` button to `my profile` or something similar

**Comment by zacjones93** [comment]
Looks good @CharlieTyler!

I agree with Jared, the buttons should change based on a user being signed in or not. That is an easy thing to adjust as we build these out.

I hadn't thought of displaying previous moves in a list like that on the side, makes total sense though.

The 'friends' feature seems to me like a stretch goal.
