### ISSUE TITLE
Plan out Database model

### ISSUE THREAD

**Issue by apolishch** [apolishch/dreamteam#9]
- [x] Try and come up with the easiest way to model a normal chessgame. 
- [x] Don't worry about things that are way in the future (e.g. ELO calculations, or stalemate tracking)
Model movement, pieces, games, victory, positions
- [x] Bring this one up for discussion, talk to Abe as well
- [x] Just use Excel/Google Sheets or whatever similar tool you want

**Comment by hanshank** [comment]
Link to excel spread sheet with plans:
https://1drv.ms/x/s!AvrVl0wDXWEgkq5zXax5BmX78SWr0w
